#!/usr/bin/env python3
"""
Interactive setup for AI Trading Platform.
1) Python 3.11+  2) venv  3) deps  4) CUDA  5) .env
6) DB  7) models  8) Bybit test  9) run instructions
"""
from __future__ import annotations

import os
import secrets
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
VENV_DIR = ROOT / ".venv"
REQUIREMENTS = ROOT / "requirements.txt"


def info(msg: str) -> None:
    print(f"\033[92m✓\033[0m {msg}")


def warn(msg: str) -> None:
    print(f"\033[93m!\033[0m {msg}")


def err(msg: str) -> None:
    print(f"\033[91m✗\033[0m {msg}")


def check_python() -> None:
    if sys.version_info < (3, 11):
        err(f"Python 3.11+ required, found {sys.version}")
        sys.exit(1)
    info(f"Python {sys.version.split()[0]}")


def ensure_venv() -> Path:
    if VENV_DIR.exists():
        info(f"Virtualenv exists: {VENV_DIR}")
    else:
        subprocess.check_call([sys.executable, "-m", "venv", str(VENV_DIR)])
        info(f"Created virtualenv: {VENV_DIR}")
    if os.name == "nt":
        return VENV_DIR / "Scripts" / "python.exe"
    return VENV_DIR / "bin" / "python"


def install_deps(py: Path) -> None:
    subprocess.check_call([str(py), "-m", "pip", "install", "--upgrade", "pip"])
    subprocess.check_call([str(py), "-m", "pip", "install", "-r", str(REQUIREMENTS)])
    info("Dependencies installed from requirements.txt")


def check_cuda(py: Path) -> None:
    code = (
        "import torch;"
        "print('cuda', torch.cuda.is_available());"
        "print('device', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'cpu')"
    )
    try:
        out = subprocess.check_output([str(py), "-c", code], text=True)
        print(out.strip())
        if "cuda True" in out:
            info("CUDA available — PyTorch will use GPU")
        else:
            warn("CUDA not available — training will use CPU")
    except Exception as exc:
        warn(f"Could not probe CUDA: {exc}")


def prompt(text: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    val = input(f"{text}{suffix}: ").strip()
    return val or default


def create_env(py: Path) -> None:
    env_path = ROOT / ".env"
    print("\n=== Credentials (.env) ===")
    print("Keys are stored only in .env (never hardcoded). Testnet by default.\n")

    api_key = prompt("Bybit API Key (Testnet)")
    api_secret = prompt("Bybit API Secret (Testnet)")
    tg_token = prompt("Telegram Bot Token")
    tg_chat = prompt("Your Telegram Chat ID")
    dash_user = prompt("Dashboard username", "admin")
    dash_pass = prompt("Dashboard password", "admin")
    jwt_secret = secrets.token_urlsafe(32)

    # Hash password via venv python
    hash_code = (
        "from security.passwords import hash_password; "
        f"print(hash_password({dash_pass!r}))"
    )
    try:
        pwd_hash = subprocess.check_output(
            [str(py), "-c", hash_code],
            cwd=str(ROOT),
            text=True,
        ).strip()
    except Exception:
        # Fallback if package import path not ready yet
        import bcrypt

        pwd_hash = bcrypt.hashpw(dash_pass.encode(), bcrypt.gensalt(12)).decode()

    enc_key = secrets.token_urlsafe(32)

    content = f"""# Generated by setup.py — do not commit
BYBIT_API_KEY={api_key}
BYBIT_API_SECRET={api_secret}
BYBIT_TESTNET=true
BYBIT_BASE_URL=https://api-testnet.bybit.com

TELEGRAM_BOT_TOKEN={tg_token}
TELEGRAM_CHAT_ID={tg_chat}

DASHBOARD_USERNAME={dash_user}
DASHBOARD_PASSWORD_HASH={pwd_hash}
JWT_SECRET={jwt_secret}
SESSION_TTL_HOURS=24

INITIAL_BALANCE=10000
MAX_DAILY_LOSS_PCT=3.0
MAX_POSITION_PCT=5.0
DEFAULT_LEVERAGE=5
TRADING_PAIRS=BTCUSDT,ETHUSDT,SOLUSDT

ENV_ENCRYPTION_KEY={enc_key}
FORCE_HTTPS=true
RATE_LIMIT=60/minute

LOG_LEVEL=INFO
TIMEZONE=Europe/Kyiv
DASHBOARD_HOST=0.0.0.0
DASHBOARD_PORT=8080
"""
    env_path.write_text(content, encoding="utf-8")
    os.chmod(env_path, 0o600)
    info(f"Wrote {env_path}")

    # Encrypt mirror
    try:
        enc_code = "from security.env_crypto import encrypt_env_file; print(encrypt_env_file())"
        out = subprocess.check_output([str(py), "-c", enc_code], cwd=str(ROOT), text=True)
        info(f"Encrypted env → {out.strip()}")
    except Exception as exc:
        warn(f"Could not encrypt .env yet: {exc}")


def init_database(py: Path) -> None:
    code = "from core.database import init_db; init_db(); print('db_ok')"
    out = subprocess.check_output([str(py), "-c", code], cwd=str(ROOT), text=True)
    if "db_ok" in out:
        info("Database initialized (data/trading.db)")


def load_pretrained_models(py: Path) -> None:
    models_dir = ROOT / "data" / "models"
    models_dir.mkdir(parents=True, exist_ok=True)
    existing = [p for p in models_dir.iterdir() if p.suffix in {".pt", ".joblib", ".json"}]
    if existing:
        info(f"Found pretrained artifacts: {[p.name for p in existing]}")
        return
    warn("No pretrained models found — will train a first checkpoint from Testnet data")
    try:
        subprocess.check_call(
            [str(py), str(ROOT / "main.py"), "--train"],
            cwd=str(ROOT),
        )
        info("Initial model training finished")
    except Exception as exc:
        warn(f"Initial training skipped/failed (you can run later): {exc}")


def test_bybit(py: Path) -> None:
    code = (
        "from core.bybit_client import BybitClient; "
        "r=BybitClient().test_connection(); "
        "print(r); "
        "raise SystemExit(0 if r.get('ok') else 1)"
    )
    try:
        out = subprocess.check_output([str(py), "-c", code], cwd=str(ROOT), text=True)
        print(out)
        info("Bybit connection test OK")
    except subprocess.CalledProcessError as exc:
        err("Bybit connection test failed — check API keys / IP whitelist")
        if exc.output:
            print(exc.output)
        warn("You can still start the bot; public market data may work without keys")


def print_instructions() -> None:
    print(
        """
═══════════════════════════════════════════════
  SETUP COMPLETE — How to run
═══════════════════════════════════════════════

Activate venv:
  source .venv/bin/activate        # Linux/macOS
  .venv\\Scripts\\activate         # Windows

Start platform (engine + HTTPS dashboard):
  python main.py

Open dashboard:
  https://localhost:8080
  (accept self-signed certificate warning)

Default login: credentials you entered in setup

Useful commands:
  python main.py --once           # one scan cycle
  python main.py --train          # retrain ML models
  python main.py --daily-update   # full nightly pipeline
  python main.py --watchdog       # auto-restart supervisor
  python main.py --no-dashboard   # engine only

Bybit Testnet keys:
  https://testnet.bybit.com/ → Account → API

Telegram bot:
  Talk to @BotFather → /newbot → copy token
  Get your chat id via @userinfobot

IP whitelist:
  Add this machine's public IP in Bybit API key settings.
"""
    )


def main() -> int:
    print("AI Trading Platform — setup\n")
    check_python()
    py = ensure_venv()
    install_deps(py)
    check_cuda(py)
    create_env(py)
    init_database(py)
    load_pretrained_models(py)
    test_bybit(py)
    print_instructions()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
